version: "3"
services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: bolinha@32142970
            MYSQL_DATABASE: projects_management_server
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    backend:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app
        environment:
            NODE_ENV: development
        env_file:
            - ./backend/.env
        depends_on:
            - mysql
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
        environment:
            NODE_ENV: development
        depends_on:
            - backend

volumes:
    mysql-data:
